### ISSUE TITLE
UPDATE sqls not working

### ISSUE THREAD

**Issue by RichardMillerWimmer** [boardgame-project/boardgame-project#40]
updateReview and updateRating seem to be sending correct body with session.user but not updating the database.  Debugged to the point of narrowing it to the .sql or database issue.

**Comment by djkoser** [comment]
Unable to update user_games -> temporarily fixed by changing game_id text field to varchar(10). Re-testing pending.

**Comment by djkoser** [comment]
Following retesting, it was determined that duplicate user-game_id entries were causing postgres to be unable to find the prescribed set column. Test data was updated accordingly and the issue is now resolved.
